### ISSUE TITLE
Nice 

### ISSUE THREAD

**Issue by issac756** [Team-BANERUS/poketwo-Autocatcher#14]
Sure my bad

**Comment by HOPE-NEXUS** [comment]
okay malik,i thought u as a friend till now,
and thought to let it go as casual.
but you have challenged me so let's begin!

When are you going to return my 12-14 or 16k INR (ur country currency)
and you hired a freelancer with my money to create your cheap autocatcher and that's lame.

if you still want more expose, just comment once more.

If you would like to delete it, close the issue urself and change the title of the issue.

Let the fun begin baby.

**Comment by HOPE-NEXUS** [comment]
also you have only 10mins, i will be waiting.

Also dont worry I intend to make it better , I will reach ya cuz you are my old fake-friend who took my money, correct your fake-rich errors inside you, when you are done playing with your teddy bear.

**Comment by issac756** [comment]
Nice kid you assumed I'm malik how pog you are lmfao

**Comment by issac756** [comment]
And if it's with malik go take to his dms

**Comment by HOPE-NEXUS** [comment]
issac = malik
maybe now garry/shitsuren/anos into that alt.

And don't act lame, either you are related to them,
and if you are not malik then you know what to do.

**Comment by HOPE-NEXUS** [comment]
i don't need to give free suggestions sorry,
already gave you plenty to copy lol.

**Comment by issac756** [comment]
Oh yea?

**Comment by issac756** [comment]
Get good .

**Comment by HOPE-NEXUS** [comment]
> 
> 
> Get good .

my deeds are clear, karma exists,
i just fix the appointments.

**Comment by HOPE-NEXUS** [comment]
oh okay, you deleted you comment,
so you want me to delete this issue
or keep it here?

**Comment by issac756** [comment]
So either you slow on intake , or failed to notice it .

**Comment by HOPE-NEXUS** [comment]
ah good, you deleted your comment to give a feeling of "being right here" by hiding how it started.
such a FAKE actions you do my fake friend.

**Comment by issac756** [comment]
Got you next time , I will rember that

**Comment by issac756** [comment]
Also I ain't the guys you named above, im the one who is a freelance (that's what you call) , so if you got anything with them take to their dms.

**Comment by HOPE-NEXUS** [comment]
> 
> 
> Also I ain't the guys you named above, im the one who is a freelance (that's what you call) , so if you got anything with them take to their dms.

I don't think malik told you about me, we used to good friends.

and the guy who freelance, hahah.
malik's 2nd alt was Issac and you own that alt lmfao?
i myself setup `ac for Issac alt` 6months ago or somewhat ig.

and can you just stop being fake?

shitsuren = anos
issac = malik

that's simple logic you can fit into your brain?

or you are the 3rd guy but having the name Issac on your github?

**Comment by HOPE-NEXUS** [comment]
also,if you dont delete your comment,

it proves malik scammed me, and used my money to hire freelancer.

thanks for clearing out the point as scammers don't have the guts themself to admit.

**Comment by HOPE-NEXUS** [comment]
BRO,YOU JUST DELETED YOUR COMMENTS , SUCH A SAD DICK.

GOT EXPOSED OR SOMETHING?

NEXT TIME DON'T TIME TO MESS UP WITH ME, YOU WILL GET GANDBANGED.
AUR JAH TOHDA MUH DHOLE, WARNA GUILT NA HO TUJHE

**Comment by HOPE-NEXUS** [comment]
> 
> 
> Let's do this

okay so you learnt few sense in these 10mins you went?

**Comment by issac756** [comment]
Right so do I look like 18 kid , I got life

**Comment by issac756** [comment]
Lmfao right 😂 it's good let's keep it goin

**Comment by issac756** [comment]
Who cares who was malik to you, do I look I care

**Comment by issac756** [comment]
Fake people oh yea did I forget how your so called ai got hundreds of people banned cuz someone claimed it's ai what a dick ?

**Comment by issac756** [comment]
So if you want yea lets keep this goin shall we.

**Comment by HOPE-NEXUS** [comment]
> 
> 
> Fake people oh yea did I forget how your so called ai got hundreds of people banned cuz someone claimed it's ai what a dick ?

prove it.
and if you are thinking about using this dumb method to distract from real point, i am not fake like you, and I have manners to not to scam people,i still follow my ethics.

**Comment by issac756** [comment]
Prove of yea sure

**Comment by issac756** [comment]
You can't keep you client info safe , how good can you be

**Comment by issac756** [comment]
I don't need a distraction , truth always hurts

**Comment by issac756** [comment]
P.s rember it's what you asked , people ain't that dumb buddy if you piss off someone you get pissed off too

**Comment by issac756** [comment]
If you got prob with malik take to him simple as that , don't bother to waste my time

**Comment by HOPE-NEXUS** [comment]
> 
> 
> You can't keep you client info safe , how good can you be

Second proof, you are not the freelancer so just shut lmao.

And let me tell one more thing,
when you bought my autocatcher around 5-6months or smthing ago.

you did not even knew how to fork it,
i thought you about it.
moreover when you used to run your scam server of gambling that u told me about it,
and i setup 4autocatcher for u,
but later you forked the repl that was private and PUT UR FUCKING TOKEN OF ISSAC INTO PUBLIC FILE.
Whereas i told not to.

and it's second proof you are Malik.

**Comment by issac756** [comment]
Thank you , I m closing this do as you wish with comments

**Comment by issac756** [comment]
Who are you numb skull

**Comment by HOPE-NEXUS** [comment]
> 
> 
> I don't need a distraction , truth always hurts

Being exposed with real facts, break you up.
and truth hurts when it is actual truth, not when someone makes it by himself and act so cool.

**Comment by issac756** [comment]
It's actual truth stop hiding behind your mom kiddo

**Comment by issac756** [comment]
You never touched my repo
On to the point why would I use hint to auto do I look dumb buddy ,

**Comment by HOPE-NEXUS** [comment]
> 
> 
> Who are you numb skull

you can close it but i won;t delete the issue as well the comments by me , although you deleted ur comments and just go and piss the *i won't tell her name due to privacy, but u can understand who*

**Comment by HOPE-NEXUS** [comment]
> 
> 
> You never touched my repo
> On to the point why would I use hint to auto do I look dumb buddy ,

Bro can u just talk straight?
i never said you use hint in your so cheap github issue.

and why i opened was you copied many things of my github repo

AND KINDLY MENTIONED IN ISSUE, TO CHANGE IT.

and you take it to your ego and not improvements

**Comment by HOPE-NEXUS** [comment]
BRO CAN YOU JUST STOP EDITING YOUR COMMENTS,
THAT'S IRRITATING NO POINT OF TALKING TO SUCH FAKE FRIEND OR WHATEVER CHEAP TAGS YOU GOT.

**Comment by issac756** [comment]
Thing was ego

**Comment by issac756** [comment]
It the way of asking

**Comment by HOPE-NEXUS** [comment]
I Hear everything they be saying about me,
Just don't wake me up, if it's not about me,

You know how this reality go,
if you being on a reality show
Then you Ain't got to stop me.

Exposing me, seems like a lame joke, (x2)
You be talking Fake shit, Fuck you're fake Bro,
--
You know nexus is real, when i arrive you being hiding in fear,
Can you stop roleplaying coz it's not your lying mirror.
