### ISSUE TITLE
Few perfect lines for you, take them as tip from me.

### ISSUE THREAD

**Issue by issac756** [Team-BANERUS/poketwo-Autocatcher#15]
Few perfect lines for you, take them as tip from me.

.

**I Hear everything they be saying about me,**
**Just don't wake me up, if it's not about me,**

**You know how this reality go,**
**if you being on a reality show**
**Then you Ain't got to stop me.**

**Exposing me, seems like a lame joke, (x2)**
**You be talking Fake shit, Fuck you're fake Bro,**
__
**You know nexus is real, when i arrive you being hiding in fear,**
**Can you stop roleplaying coz it's not your lying mirror.**

_Originally posted by @HOPE-NEXUS in https://github.com/Team-BANERUS/poketwo-Autocatcher/issues/14#issuecomment-892927868_

**Comment by issac756** [comment]
Yes I can see whose lame here , you are pissin hard my boy just stfu and you got no guts 😂 stop closing your own issue and then send comments

**Comment by issac756** [comment]
I don't need to expose some fake shit right

**Comment by issac756** [comment]
Yes turn 25 first then let's talk about fear image kids having guts to talk about fear

**Comment by HOPE-NEXUS** [comment]
Thanks for posting the lyrics here from #14 !
