### ISSUE TITLE
Lmfao 

### ISSUE THREAD

**Issue by issac756** [Team-BANERUS/poketwo-Autocatcher#18]
May be I should say now nice working doin crappy job bro 😂 (write your own code, not simply copy someone's readme) smh you cares and it was nice clickbait to in video it proves Nothin lol anyways good luck scamming as all ways

**Comment by issac756** [comment]
Lol light weight sure imagine using api but not using own trained models can't be me.

**Comment by Futureslinky** [comment]
Hey, you guys just want few Views from Banerus GitHub, lmao.
We all know who's Real and Fake

Real = Banerus
Fake = Malik/Issac/xiu ye/tokagarry/shitsuren

Also, you remember when you joined VC (voice) on discord.
You were constantly being roasted you didn't have a word to say lol.

Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views

Alright, before you deny that you copied Hyperclaws code let's look at an image shall we? 
![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)

Now please shut up before you get exposed even more.

**Comment by Futureslinky** [comment]
How much more do you want to be roasted and exposed?
Check #14 where you were exposed.
Also, I'm dropping a screenshot of your comment because you scammers keep editing and deleting your comments

![image](https://user-images.githubusercontent.com/77411358/128646352-2f6e5216-8c7d-48a8-8575-9b08b36ce0d6.png)

**Comment by HOPE-NEXUS** [comment]
Who is this 'Issac'?
Oh he is another Poketwo autocatcher seller but a copy lmao,
that's so dumb.

@issac756 can you stop coming here and sharing your personal views about it?

like none knows, you but anyways you are exposed here and #14 isssue.

**Comment by HOPE-NEXUS** [comment]
Unlocked the issue, to see the shitty reply from @issac756 .
I know he checks our github everyday , hope he doesn't ignore this

**Comment by issac756** [comment]
> Hey, you guys just want few Views from Banerus GitHub, lmao.
> We all know who's Real and Fake
> 
> Real = Banerus
> Fake = Malik/Issac/xiu ye/tokagarry/shitsuren
> 
> Also, you remember when you joined VC (voice) on discord.
> You were constantly being roasted you didn't have a word to say lol.
> 
> Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views
> 
> Alright, before you deny that you copied Hyperclaws code let's look at an image shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
> That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)
> 
> Now please shut up before you get exposed even more.

Who are you a guy with 0 coding knowlege , yea before goin that what are you dog of nexus thanks for reminding me that I'm better off not using repl as hosting service , you don't get to speak when you donno the diff so please shut lol why so much pity . Get good using 3rd party api you are worst so man we will talk when you are good right

**Comment by issac756** [comment]
> How much more do you want to be roasted and exposed?
> Check #14 where you were exposed.
> Also, I'm dropping a screenshot of your comment because you scammers keep editing and deleting your comments
> 
> ![image](https://user-images.githubusercontent.com/77411358/128646352-2f6e5216-8c7d-48a8-8575-9b08b36ce0d6.png)

>Before calling other fools what are you lol , not to mention not a copy cat and trust me I don't need to edit my comments you loosers 
![Uploading IMG_20210809_203531_807.jpg…]()

**Comment by issac756** [comment]
> Who is this 'Issac'?
> Oh he is another Poketwo autocatcher seller but a copy lmao,
> that's so dumb.
> 
> @issac756 can you stop coming here and sharing your personal views about it?
> 
> like none knows, you but anyways you are exposed here and #14 isssue.
> 
> Thanks, @Futureslinky for exposing him off.

Yes better than you dumbass I better not block the people I scammed

**Comment by issac756** [comment]
> Who is this 'Issac'?
> Oh he is another Poketwo autocatcher seller but a copy lmao,
> that's so dumb.
> 
> @issac756 can you stop coming here and sharing your personal views about it?
> 
> like none knows, you but anyways you are exposed here and #14 isssue.
> 
> Thanks, @Futureslinky for exposing him off.

Yes better than you dumbass I better not block the people I scammed

**Comment by issac756** [comment]
> Hey, you guys just want few Views from Banerus GitHub, lmao.
> We all know who's Real and Fake
> 
> Real = Banerus
> Fake = Malik/Issac/xiu ye/tokagarry/shitsuren
> 
> Also, you remember when you joined VC (voice) on discord.
> You were constantly being roasted you didn't have a word to say lol.
> 
> Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views
> 
> Alright, before you deny that you copied Hyperclaws code let's look at an image shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
> That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)
> 
> Now please shut up before you get exposed even more.

And please shut you up you don't get to talk when you weren't banned or aisptn

**Comment by issac756** [comment]
> How much more do you want to be roasted and exposed?
> Check #14 where you were exposed.
> Also, I'm dropping a screenshot of your comment because you scammers keep editing and deleting your comments
> 
> ![image](https://user-images.githubusercontent.com/77411358/128646352-2f6e5216-8c7d-48a8-8575-9b08b36ce0d6.png)



> Hey, you guys just want few Views from Banerus GitHub, lmao.
> We all know who's Real and Fake
> 
> Real = Banerus
> Fake = Malik/Issac/xiu ye/tokagarry/shitsuren
> 
> Also, you remember when you joined VC (voice) on discord.
> You were constantly being roasted you didn't have a word to say lol.
> 
> Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views
> 
> Alright, before you deny that you copied Hyperclaws code let's look at an image shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
> That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)
> 
> Now please shut up before you get exposed even more.

>yep Banerus very real not to mention 
![proof](![proof](https://cdn.discordapp.com/attachments/867696784167403530/874309629474123806/Screenshot_20210809-204407.jpg)
![proof1](https://cdn.discordapp.com/attachments/867696784167403530/874309560704307300/IMG_20210809_203531_807.jpg)
>p.s i really dont need to edit my comments

**Comment by issac756** [comment]
> Hey, you guys just want few Views from Banerus GitHub, lmao.
> We all know who's Real and Fake
> 
> Real = Banerus
> Fake = Malik/Issac/xiu ye/tokagarry/shitsuren
> 
> Also, you remember when you joined VC (voice) on discord.
> You were constantly being roasted you didn't have a word to say lol.
> 
> Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views
> 
> Alright, before you deny that you copied Hyperclaws code let's look at an image shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
> That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
> ![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)
> 
> Now please shut up before you get exposed even more.

who are you kidding lol , using chromium + plus 3rd part api to solve captcha people arent that dumb bro. and yea did anyone failed to mention nexus was trying to copy hypers too but his brain wasnt smart so he failed and oh yea i have his dms proof asking this about can i share hypers code so dont even waste time arguing.

**Comment by issac756** [comment]
being a third wheel is good , but try to butt in when you think you are good when you suck same as nexus . you better off mind your own shit

**Comment by issac756** [comment]
> How much more do you want to be roasted and exposed?
> Check #14 where you were exposed.
> Also, I'm dropping a screenshot of your comment because you scammers keep editing and deleting your comments
> 
> ![image](https://user-images.githubusercontent.com/77411358/128646352-2f6e5216-8c7d-48a8-8575-9b08b36ce0d6.png)

lmfao sure lol 
![proof](https://cdn.discordapp.com/attachments/867696784167403530/874315369366564904/Screenshot_20210809-210652.jp)
>Note this was totally a scammer hidding his tracks , do a good background search before you even speak .

**Comment by issac756** [comment]
It the same thing why you even have hypers code , cuz you failed (not that I excepted you to make it working ) and before speaking the facts try comparing it lol , so much for creating custom gui , for autocatcher and a website to control all , big talk .

**Comment by issac756** [comment]
So yea , question you think you are smart but you aren't and you know why I created a issue ask yourself. Adding more comments don't make me bring in all dms , to actually show whose real Oki , hope you had a nice day .

**Comment by issac756** [comment]
> Who is this 'Issac'?
> Oh he is another Poketwo autocatcher seller but a copy lmao,
> that's so dumb.
> 
> @issac756 can you stop coming here and sharing your personal views about it?
> 
> like none knows, you but anyways you are exposed here and #14 isssue.
> 
> Thanks, @Futureslinky for exposing him off.

My bad 
You are exposed here 
![lmfao](https://github.com/Team-BANERUS/poketwo-Autocatcher/issues/18#issuecomment-895332560)

**Comment by HOPE-NEXUS** [comment]
> 
> 
> > Hey, you guys just want few Views from Banerus GitHub, lmao.
> > We all know who's Real and Fake
> > Real = Banerus
> > Fake = Malik/Issac/xiu ye/tokagarry/shitsuren
> > Also, you remember when you joined VC (voice) on discord.
> > You were constantly being roasted you didn't have a word to say lol.
> > Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views
> > Alright, before you deny that you copied Hyperclaws code let's look at an image shall we?
> > ![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
> > That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
> > ![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)
> > Now please shut up before you get exposed even more.
> 
> Yea good one Harshit did you try our free trail so what's the baseless assumption
> 
> > Note : people who run 100 auto gets no right to talk plus , it must be like this nexus should have asked you to support him so you can get free auto cuz you broke ass can't afford one irl
> > .
> > Just wondering what's your level of coding just hosting / running one auto successfully on repl.it doesn't count as coding my guy .
> > So yea now shut up before I expose you more . Get good at coding then we talk
-----------------------------------------------------------------------------------------------------

-_- trial does not have terminal shown

**Comment by HOPE-NEXUS** [comment]
> 
> 
> > How much more do you want to be roasted and exposed?
> > Check #14 where you were exposed.
> > Also, I'm dropping a screenshot of your comment because you scammers keep editing and deleting your comments
> > ![image](https://user-images.githubusercontent.com/77411358/128646352-2f6e5216-8c7d-48a8-8575-9b08b36ce0d6.png)
> 
> lmfao sure lol
> ![proof](https://camo.githubusercontent.com/f9fafc2ad72ad4c1e280f6e60201d563e15731bc5e5880dbd66bf2b98669eb0a/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3836373639363738343136373430333533302f3837343331353336393336363536343930342f53637265656e73686f745f32303231303830392d3231303635322e6a7067)
> 
> > Note this was totally a scammer hidding his tracks , do a good background search before you even speak .

yeah i already said why i deleted those lol in issue fourteen

**Comment by HOPE-NEXUS** [comment]
> 
> 
> > Hey, you guys just want few Views from Banerus GitHub, lmao.
> > We all know who's Real and Fake
> > Real = Banerus
> > Fake = Malik/Issac/xiu ye/tokagarry/shitsuren
> > Also, you remember when you joined VC (voice) on discord.
> > You were constantly being roasted you didn't have a word to say lol.
> > Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views
> > Alright, before you deny that you copied Hyperclaws code let's look at an image shall we?
> > ![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
> > That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
> > ![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)
> > Now please shut up before you get exposed even more.
> 
> who are you kidding lol , using chromium + plus 3rd part api to solve captcha people arent that dumb bro. and yea did anyone failed to mention nexus was trying to copy hypers too but his brain wasnt smart so he failed and oh yea i have his dms proof asking this about can i share hypers code so dont even waste time arguing.

Welp u dont code so take my free lesson:

2captcha or any other returns g-captcha response, which is later on to be filled in the output/somewhere in html tags.
The reason i showed browser was by using 3rd party apps , you can't make it click on imgs.
this automation was done using Selenium n ai , not charging extra
ask someone lol.

**Comment by HOPE-NEXUS** [comment]
"to mention nexus was trying to copy hypers too but his brain wasnt smart so he failed and oh yea i have his dms proof asking this about can i share hypers code so dont even waste time arguing."
 By Malik newton.
 
 Oh jesus, Coding have different langs and you can't easily convert their lang.
 Banerus = Js
 Hyper = py
So,what's the point of copying?

it is not the translator you use for understanding english or converting.

**Comment by HOPE-NEXUS** [comment]
> 
> 
> > How much more do you want to be roasted and exposed?
> > Check #14 where you were exposed.
> > Also, I'm dropping a screenshot of your comment because you scammers keep editing and deleting your comments
> > ![image](https://user-images.githubusercontent.com/77411358/128646352-2f6e5216-8c7d-48a8-8575-9b08b36ce0d6.png)
> 
> > Hey, you guys just want few Views from Banerus GitHub, lmao.
> > We all know who's Real and Fake
> > Real = Banerus
> > Fake = Malik/Issac/xiu ye/tokagarry/shitsuren
> > Also, you remember when you joined VC (voice) on discord.
> > You were constantly being roasted you didn't have a word to say lol.
> > Yeah continue your fake comments, he knows you are just a dumbass who copied @Hyperclaw79 codes and can you stop commenting here for views
> > Alright, before you deny that you copied Hyperclaws code let's look at an image shall we?
> > ![image](https://user-images.githubusercontent.com/77411358/128645744-1926e255-756b-4d69-aa00-789946c20f0c.png)
> > That's your Ai Catcher, we can clearly see that you stole @Hyperclaw79 code and added a captcha solver. Fool you think no one would notice that? Everyone knows you paid a person to add the captcha solver thanks to this website [Captcha Solver](https://screenshot.best/E7E5NI). And let's look at @Hyperclaw79 Ai shall we?
> > ![image](https://user-images.githubusercontent.com/77411358/128646121-dd9bbb6c-d58d-4759-8020-dc1fb22c496c.png)
> > Now please shut up before you get exposed even more.
> 
> > yep Banerus very real not to mention
> > ![proof](![proof](https://camo.githubusercontent.com/8511de5ae2c6ee5cb4585848fe2387460c5f9607b6040270e1f8544afb191ce1/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3836373639363738343136373430333533302f3837343330393632393437343132333830362f53637265656e73686f745f32303231303830392d3230343430372e6a7067)
> > ![proof1](https://camo.githubusercontent.com/6c14a2556815811fa069c19e7c6a0a2700063e004f6a36d0f8dbf5ef11fbea85/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3836373639363738343136373430333533302f3837343330393536303730343330373330302f494d475f32303231303830395f3230333533315f3830372e6a7067)
> > p.s i really dont need to edit my comments
---------------------------------------------------
'p.s i really dont need to edit my comments'
by malik newton

I do edit my comments to fix few spelling mistakes and not causing a dramatic change in the meaning.
I have learnt from mistakes, not like you try to piss who told the mistakes.
Big difference between Leader n Cheater

Welp, anyone can make fake ss , lol.
Someone from 'anime vibes' commented saying he purchased the program 2days ago n he was asked to buy aidex premium token, i knew it was you but i removed the comment.
how i knew it was you:
it was 2days n aidex is merge of ourself n the devs, so we dont charge within 2days lol.

Expand ur knowledge baby.

**Comment by HOPE-NEXUS** [comment]
also you are using same fake ss proof again n again.

Lol, whom are we fighting to?
having guilt scolding a kid malik newton.

**Comment by issac756** [comment]
> also you are using same fake ss proof again n again.
> 
> Lol, whom are we fighting to?
> having guilt scolding a kid malik newton.

Question is you ain't some big shot my guy so people will go around make fake screenshot aganist you . You aren't even worth trying that those screenshot are from the people who pissed you off .

**Comment by issac756** [comment]
> > > How much more do you want to be roasted and exposed?
> > > Check #14 where you were exposed.
> > > Also, I'm dropping a screenshot of your comment because you scammers keep editing and deleting your comments
> > > ![image](https://user-images.githubusercontent.com/77411358/128646352-2f6e5216-8c7d-48a8-8575-9b08b36ce0d6.png)
> > 
> > 
> > lmfao sure lol
> > ![proof](https://camo.githubusercontent.com/f9fafc2ad72ad4c1e280f6e60201d563e15731bc5e5880dbd66bf2b98669eb0a/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3836373639363738343136373430333533302f3837343331353336393336363536343930342f53637265656e73686f745f32303231303830392d3231303635322e6a7067)
> > > Note this was totally a scammer hidding his tracks , do a good background search before you even speak .
> 
> yeah i already said why i deleted those lol in issue fourteen

> No you didn't , either you are missing some pieces of your memory or me .

**Comment by issac756** [comment]
You are a joke , mate I don't need to hide my ip adreess that's for someone who's just stupid .
"13 yr" old kid grabbed your ip get good he's just another kid like you at the end , you and him made cyber security a joke.

**Comment by HOPE-NEXUS** [comment]
Lmfao. You joke.

**Comment by HOPE-NEXUS** [comment]
> 
> 
> > also you are using same fake ss proof again n again.
> > Lol, whom are we fighting to?
> > having guilt scolding a kid malik newton.
> 
> Question is you ain't some big shot my guy so people will go around make fake screenshot aganist you . You aren't even worth trying that ,those screenshot are from the people who you pissed off.
> P.S On brighter side , did you forget how much you suck at speaking English , may be you are still using the translator cuz even the words you speak ain't perfect yet and there's the difference btw editing two lines of comments And editing whole paragraph to look cool & deleting comments to look way cooler then ack like shit .

repeating speaking-speaking again sounds dumb - use "pronunciation" I dont want to teach you more.
anway i dont have time to even reply you out and especially reading such unprofessional comments
