### ISSUE TITLE
Discord link error

### ISSUE THREAD

**Issue by JohnnyAppleseed132** [Team-BANERUS/poketwo-Autocatcher#4]
Discord server link error produces a 404 page not found when clicked on.

**Comment by HOPE-NEXUS** [comment]
remove the github.com from the redirect link and It Will Work. it is done to handle Junk joins.

**Comment by diegoPB31** [comment]
I removed github.com but I still can't find the discord link, what should I do?

**Comment by HOPE-NEXUS** [comment]
> 
> 
> I removed github.com but I still can't find the discord link, what should I do?

Updated the link, friend try now
