### ISSUE TITLE
Very very detectable

### ISSUE THREAD

**Issue by Hyperclaw79** [Team-BANERUS/poketwo-Autocatcher#5]
You got 500 accounts banned lmao, how does it feel?
Stop making false claims.

**Comment by HOPE-NEXUS** [comment]
Woah, 500accounts.
i mean why are you spreading False Information.
well,be ready man- no More Patience.
i Had my Final Exams (ends on 15/16 march)
Then i will Surly give u Reply of This and You have reached the Limit of Hatred and Jealously i Can Take.

**Comment by Hyperclaw79** [comment]
It's too late mate, many peeps already know what you've been up to, no point in trying to play it safe
