### ISSUE TITLE
Readme is a rip-off

### ISSUE THREAD

**Issue by Hyperclaw79** [Team-BANERUS/poketwo-Autocatcher#6]
I can still see the copy pastes in your readme from my my repo. Forked my repo to steal more eh?

**Comment by HOPE-NEXUS** [comment]
What did i Copy and paste?
Also,why are you opening such too many issues lol.

**Comment by Hyperclaw79** [comment]
You might wanna take a look at your readme once to answer your question.

Can't help opening too many issues, if there are too many issues to point out 🤷🏻
